[package]
name = "year2015"
description = "My take on Advent of Code 2015 in Rust"
version = "0.3.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
keywords.workspace = true

[lib]
doctest = false
