[package]
name = "year2023"
description = "My take on Advent of Code 2023 in Rust"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
keywords.workspace = true

[dependencies]
aho-corasick = "1.1.2"

[lib]
doctest = false
